### ISSUE TITLE
why am i getting this and i already downloaded all packages/dep

### ISSUE THREAD

**Issue by ghost** [redtardis12/Sky-Keys-interactive#1]
PS C:\Users\sh4vear\desktop\Sky-Keys-interactive> python app.py
Traceback (most recent call last):
  File "C:\Users\sh4vear\desktop\Sky-Keys-interactive\app.py", line 8, in <module>
    from music.automusic import mstart
  File "C:\Users\sh4vear\desktop\Sky-Keys-interactive\music\automusic.py", line 3, in <module>
    import keyboard                               python app.py
>> uleNotFoundError: No module named 'keyboard'

**Comment by redtardis12** [comment]
Newest python versions stopped including some modules, i added the dependencies file, so there won't be any issues. Clone the new repository and type:
```bash
pip install -r requirements.txt
```
Instructions are updated is Readme.md

You can also [download](https://github.com/redtardis12/Sky-Keys-interactive/releases/tag/pre-release) the pre-release version - it doesn't require anything, just extract the archive and launch .exe
